service: serverless-crud-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: us-east-1
  deploymentMethod: direct
  environment:
    CRUD_TABLE_NAME: !Ref crudDynamoDBTable

plugins:
  - serverless-iam-roles-per-function

functions:
  createBook:
    handler: src/create-book.handler
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem        
        Resource: !GetAtt crudDynamoDBTable.Arn
    events:
      - http:
          path: /books
          method: post
          cors: true

  getBooks:
    handler: src/get-books.handler
    iamRoleStatements:
      - Effect: Allow     
        Action:
          - dynamodb:Scan        
        Resource: !GetAtt crudDynamoDBTable.Arn
    events:
      - http:
          path: /books
          method: get
          cors: true

  getBook:
    handler: src/get-book.handler
    iamRoleStatements:
      - Effect: Allow     
        Action:
          - dynamodb:GetItem        
        Resource: !GetAtt crudDynamoDBTable.Arn
    events:
      - http:
          path: /books/{id}
          method: get
          cors: true

  updateBook:
    handler: src/update-book.handler
    iamRoleStatements:
      - Effect: Allow     
        Action:
          - dynamodb:UpdateItem        
        Resource: !GetAtt crudDynamoDBTable.Arn
    events:
      - http:
          path: /books/{id}
          method: put
          cors: true

  deleteBook:
    handler: src/delete-book.handler
    iamRoleStatements:
      - Effect: Allow     
        Action:
          - dynamodb:DeleteItem        
        Resource: !GetAtt crudDynamoDBTable.Arn
    events:
      - http:
          path: /books/{id}
          method: delete
          cors: true

resources:
  Resources: ${file(resources.yml)}
