service: serverless-crud-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  deploymentMethod: direct
  environment:
    tableName: serverless-crud-table

plugins:
  - serverless-iam-roles-per-function

functions:
  createBook:
    handler: src/create-book.handler
    iamRoleStatements:
      - Effect: "Allow"        
        Action:
          - dynamodb:PutItem        
        Resource: !GetAtt CrudDynamoDBTable.Arn
    events:
      - http:
          path: /books
          method: post
          cors: true

  getBooks:
    handler: get-books.handler
    events:
      - http:
          path: /books
          method: get
          cors: true

  getBook:
    handler: get-book.handler
    events:
      - http:
          path: /books/{id}
          method: get
          cors: true

  updateBook:
    handler: create-book.handler
    events:
      - http:
          path: /books/{id}
          method: put
          cors: true

  deleteBook:
    handler: create-book.handler
    events:
      - http:
          path: /books/{id}
          method: delete
          cors: true

resources:
  Resources: ${file(resources.yml)}
